version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  faas-pigo:
    lang: golang-middleware
    handler: ./faas-pigo
    image: tri105/faas-pigo:latest
    read_timeout: 300s  
    write_timeout: 300s  
    upstream_timeout: 300s 
    exec_timeout: 300s
    environment:
      read_timeout: 300s 
      write_timeout: 300s  
      upstream_timeout: 300s 
      exec_timeout: 300s

